Dockerfile fix for buildx
elabftw/elabimg pull request #19
Opened 2021-06-18 09:45 UTC by din14970

I discovered that docker buildx behaves a bit differently than docker build. It turns out that since you updated/added some files in `./src/nginx/`, the `COPY` command on line 97 gave an error since there is already a similar named default file or folder in the destination `/etc/nginx`. For reference, the error I was getting:

```
Dockerfile:98
--------------------
  96 |     
  97 |     # copy configuration and run script
  98 | >>> COPY ./src/nginx/ /etc/nginx/
  99 |     COPY ./src/run.sh /run.sh
 100 |     COPY ./src/services /etc/services.d
--------------------
error: failed to solve: rpc error: code = Unknown desc = cannot copy to non-directory: /tmp/buildkit-mount329749225/etc/nginx/conf.d
Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = cannot copy to non-directory: /tmp/buildkit-mount329749225/etc/nginx/conf.d
```

Apparently docker build will interpret `COPY` as a hard overwrite, whereas buildx will not allow you to do this.

Removing the contents of `/etc/nginx` fixed the issue. The question is whether there are default contents in this folder that need to be conserved.

2021-06-18 09:49 UTC, NicolasCARPi commented
> The question is whether there are default contents in this folder that need to be conserved.

Nope!

2021-06-18 09:50 UTC, NicolasCARPi requested changes
You can remove the -f flag and the `/*` at the end.

2021-06-18 10:05 UTC, NicolasCARPi approved these changes

2021-06-18 10:05 UTC, merged

2021-06-18 10:06 UTC, NicolasCARPi commented
Thanks! :+1:

2021-06-19 14:05 UTC, NicolasCARPi commented
So it turns out that there are some files in there that are needed, so I commented the line for now.

2021-06-19 18:36 UTC, din14970 commented
Hmm that is unfortunate, maybe it is possible to add the default files that are necessary into `/src/nginx` to make the necessary files explicit? Otherwise with the `COPY` command it becomes a bit ambiguous what ends up in the `/etc/nginx` folder in the end.

2021-06-19 20:28 UTC, NicolasCARPi commented
I thought about it, but it doesn't look like a good approach. I think I can move common.conf, http(s).conf into conf.d, maybe create a folder for healthcheck and dhparam things, then we can have one COPY for nginx.conf and others for the folders. Shouldn't impact the size of the layers to have several instructions like that instead of one big COPY. And it would solve the buildx issues afaik.